#ifndef DEVICE_PARAMETERS
#define DEVICE_PARAMETERS

#define LCD_I2C_ADDRESS 0x27
#define LCD_ROWS 4
#define LCD_COLS 20


#define TIME_WATER_PUMP_ON_MS 20*1000L
#define TIME_BETWEEN_WATER_PUMP_ACTIVATION_MS 60*1000L

#define TIME_MIXING_PUMP_ON_MS 60*1000L

#define TIME_PERISTALTIC_PUMP_ACID_ON_MS 1*1000L
#define TIME_PERISTALTIC_PUMP_FERTILIZER_ON_MS 1*1000L


#define TIME_BETWEEN_SENSORS_READ_MS 3000 
#define TIME_BETWEEN_DISPLAY_VALUES_MS 1000 


#define THRESHOLD_VALUE_PH 2
#define THRESHOLD_TOLERANCE_PH 0.1
#define THRESHOLD_VALUE_CONDUCTIVITY 800
#define THRESHOLD_TOLERANCE_CONDUCTIVITY 50



#if defined(__AVR_ATmega168__) || defined(__AVR_ATmega328P__)
#define SERIAL_BAUDRATE 9600
#define ADC_MAX_VALUES 1024
#define ADC_MAX_VOLTAGE 5
#else 
#define SERIAL_BAUDRATE 115200
#define ADC_MAX_VALUES 4096
#define ADC_MAX_VOLTAGE 3.3
#endif
#endif
